- lib/elephant_in_the_room/sites/tag.ex
* [Fix tag delete operation](https://github.com/lambdaclass/elephant_in_the_room/pull/6/commits/d28675a99d072a000c9807aff8f729a7bbca7e24)
> (WIP) Fixes

- Makefile
- lib/elephant_in_the_room/sites/post.ex
- lib/elephant_in_the_room_web/templates/post/index.html.eex
- lib/elephant_in_the_room_web/templates/post/show.html.eex
- lib/elephant_in_the_room_web/views/post_view.ex
- mix.exs
- mix.lock
- priv/repo/migrations/20180223155619_create_posts.exs
Markdown text introduced for posts creation and display, but still not for editing because some issue related to db in master.
> markdown text introduced

- lib/elephant_in_the_room_web/templates/post/form.html.eex
- lib/elephant_in_the_room_web/views/post_view.ex
> Fix tags functionality

- lib/elephant_in_the_room_web/controllers/site_controller.ex
- lib/elephant_in_the_room_web/controllers/user_controller.ex
- lib/elephant_in_the_room_web/plug/admin.ex
- lib/elephant_in_the_room_web/router.ex
- lib/elephant_in_the_room_web/templates/layout/_admin.html.eex
- lib/elephant_in_the_room_web/templates/layout/_login_options.html.eex
- lib/elephant_in_the_room_web/templates/layout/_normal.html.eex
- lib/elephant_in_the_room_web/templates/layout/app.html.eex
- lib/elephant_in_the_room_web/templates/page/index.html.eex
- lib/elephant_in_the_room_web/templates/user/show.html.eex
- priv/repo/seeds.exs
- test/support/conn_case.ex
> enhance site navigation

- Makefile
- README.md
- `make demo_db` to create the local database, and then:
- `make demo_server` to populate the database and start the web server.
> Run Elephant with two make commands

- lib/elephant_in_the_room_web/faker/author.ex
- lib/elephant_in_the_room_web/faker/post.ex
- lib/elephant_in_the_room_web/faker/utils.ex
- lib/elephant_in_the_room_web/templates/author/public_show.html.eex
- lib/elephant_in_the_room_web/templates/layout/_normal.html.eex
- mix.exs
> Fix image generation

- assets/css/_post_card.scss
- lib/elephant_in_the_room_web/controllers/author_controller.ex
- lib/elephant_in_the_room_web/templates/author/edit.html.eex
- lib/elephant_in_the_room_web/templates/author/new.html.eex
- lib/elephant_in_the_room_web/templates/author/public_show.html.eex
- lib/elephant_in_the_room_web/templates/author/show.html.eex
- lib/elephant_in_the_room_web/templates/category/edit.html.eex
- lib/elephant_in_the_room_web/templates/category/new.html.eex
- lib/elephant_in_the_room_web/templates/role/edit.html.eex
- lib/elephant_in_the_room_web/templates/role/new.html.eex
- lib/elephant_in_the_room_web/templates/site/edit.html.eex
- lib/elephant_in_the_room_web/templates/site/new.html.eex
- lib/elephant_in_the_room_web/templates/site/public_index.html.eex
- lib/elephant_in_the_room_web/templates/tag/edit.html.eex
- lib/elephant_in_the_room_web/templates/tag/new.html.eex
- lib/elephant_in_the_room_web/views/author_view.ex
> Author public show

- Makefile
- README.md
- assets/package-lock.json
- assets/package.json
Update redme, make file, and dependencies to allow running the project with ease.
> Readme update

- assets/css/_post.scss
- lib/elephant_in_the_room_web/templates/post/public_show.html.eex
> Posts public show

- assets/css/_navbar.scss
- assets/css/_variables.scss
- assets/css/app.scss
- lib/elephant_in_the_room_web/templates/layout/_category_options.html.eex
- lib/elephant_in_the_room_web/templates/layout/_navbar.html.eex
- lib/elephant_in_the_room_web/templates/layout/_normal.html.eex
- lib/elephant_in_the_room_web/templates/layout/_site_options.html.eex
- lib/elephant_in_the_room_web/templates/layout/_user_options.html.eex
- lib/elephant_in_the_room_web/views/layout_view.ex
> Change navbar style

- assets/css/_category.scss
- assets/css/app.scss
- lib/elephant_in_the_room_web/templates/category/public_show.html.eex
> New category public show

- assets/css/_landing_page.scss
- lib/elephant_in_the_room/sites/site.ex
- lib/elephant_in_the_room_web/controllers/site_controller.ex
- lib/elephant_in_the_room_web/templates/site/_writers.html.eex
- lib/elephant_in_the_room_web/templates/site/public_show.html.eex
> Site landing: writers

- config/test.exs
- lib/elephant_in_the_room/sites/post.ex
- test/elephant_in_the_room/sites/post_test.exs
Issue fix https://github.com/lambdaclass/elephant_in_the_room/issues/119
> Markdown html scaping fix

- lib/elephant_in_the_room/sites/image.ex
- lib/elephant_in_the_room/sites/post.ex
- lib/elephant_in_the_room/sites/sites.ex
- lib/elephant_in_the_room_web/controllers/image_controller.ex
- lib/elephant_in_the_room_web/faker/post.ex
- lib/elephant_in_the_room_web/router.ex
- lib/elephant_in_the_room_web/templates/post/form.html.eex
- lib/elephant_in_the_room_web/templates/post/public_show.html.eex
- lib/elephant_in_the_room_web/templates/shared_post_card/_shared_post_card.html.eex
- lib/elephant_in_the_room_web/uploaders/image.ex
- lib/elephant_in_the_room_web/uploaders/postgresql.ex
- priv/repo/migrations/20180702183319_add_cover_and_thumbnail_to_posts.exs
- priv/repo/migrations/20180702185925_create_images.exs
- priv/repo/migrations/20180703153010_add_name_to_images.exs
- priv/repo/migrations/20180703165214_posts_use_image_and_cover.exs
- test/elephant_in_the_room/sites/sites_test.exs
> Cover or thumbnail image for posts

- README.md
- docker-compose.yml
- lib/elephant_in_the_room/application.ex
- lib/elephant_in_the_room/backup.ex
- lib/elephant_in_the_room/backup_data.ex
- lib/elephant_in_the_room_web/controllers/backup_controller.ex
- lib/elephant_in_the_room_web/router.ex
- lib/elephant_in_the_room_web/templates/backup/index.html.eex
- lib/elephant_in_the_room_web/templates/backup/no_ready_to_download.html.eex
- lib/elephant_in_the_room_web/templates/layout/_admin.html.eex
- lib/elephant_in_the_room_web/views/backup_view.ex
- priv/repo/migrations/20180703170809_create_backup_data.exs
- priv/repo/seeds.exs
Backups can be restored with:
```bash
export PGPASSWORD=postgres && \
psql -h localhost  -U postgres -c "create database elephant_in_the_room_dev;" && \
psql -h localhost  -U postgres -v ON_ERROR_STOP=1 elephant_in_the_room_dev < \
/tmp/elephant/ecto_dump/dump_2018-07-03_13:38:00.817915Z.sql
```
> Database Backup

- Makefile
- assets/css/_navbar.scss
- assets/css/_post_card.scss
- assets/css/app.scss
- assets/package-lock.json
- assets/package.json
There are some errors pending fixed
> CSS linter

- lib/elephant_in_the_room_web/controllers/post_controller.ex
- lib/elephant_in_the_room_web/templates/layout/_navbar.html.eex
- lib/elephant_in_the_room_web/templates/post/form.html.eex
This PR addresses the following issues: 
* [Change navbar 'section' to 'category'](https://github.com/lambdaclass/elephant_in_the_room/issues/166)
* Show a notification to the user when she creates a new posts.
> UI fixes (Change Sections to Categories and add notification after post creation) 

- assets/css/app.scss
- lib/elephant_in_the_room_web/faker/post.ex
- lib/elephant_in_the_room_web/faker/utils.ex
- lib/elephant_in_the_room_web/templates/site/_featured_post.html.eex
- lib/elephant_in_the_room_web/templates/site/_latest.html.eex
Issue #206 
Also fixed post generation and small changes to how images are displayed
> Post card links

- Makefile
- config/prod.exs
- docker-compose.yml
- mix.exs
now `make prod` will start the server in production mode
> Production settings

- assets/css/_landing_page.scss
- lib/elephant_in_the_room_web/templates/layout/_navbar.html.eex
> Fixed padding and removed search bar

- assets/css/_post.scss
- lib/elephant_in_the_room_web/templates/post/public_show.html.eex
> Show tags as badges

- lib/elephant_in_the_room/sites/site.ex
- lib/elephant_in_the_room_web/faker/site.ex
- priv/repo/data_generator.ex
The PR solves [this](https://github.com/lambdaclass/elephant_in_the_room/issues/230) issue.
> Fix host generation

- lib/elephant_in_the_room/sites/sites.ex
- lib/elephant_in_the_room_web/controllers/site_controller.ex
- lib/elephant_in_the_room_web/templates/site/public_show.html.eex
> Get latest posts

- lib/elephant_in_the_room_web/templates/category/public_show.html.eex
- lib/elephant_in_the_room_web/templates/layout/_navbar.html.eex
- Check for non existent authors in category view
- Change navbar 'sections' to 'category'
> Check for non existent authors in category view

- lib/elephant_in_the_room_web/templates/post/public_show.html.eex
> Removed dropcap and fixed cover aspect ratio

- lib/elephant_in_the_room_web/controllers/tag_controller.ex
- lib/elephant_in_the_room_web/templates/category/public_show.html.eex
- lib/elephant_in_the_room_web/templates/tag/public_show.html.eex
> Tags public show

- lib/elephant_in_the_room_web/views/author_view.ex
> Fixed link generation in author's posts list

- assets/css/_administration.scss
- assets/css/_navbar.scss
- assets/css/_post.scss
- assets/css/app.scss
> Improved typography

- lib/elephant_in_the_room_web/faker/author.ex
- lib/elephant_in_the_room_web/faker/post.ex
> Fix Blank image & Add columnists in auto generation

- assets/css/_post.scss
> Tag icons restyled

- lib/elephant_in_the_room_web/templates/layout/_admin.html.eex
- lib/elephant_in_the_room_web/templates/layout/_deps.html.eex
- lib/elephant_in_the_room_web/templates/layout/app.html.eex
> Faster loading time

- assets/css/_landing_page.scss
> Time position and right padding

- lib/elephant_in_the_room/sites/tag.ex
- lib/elephant_in_the_room_web/faker/tag.ex
> Add a default set of color for tags

- assets/css/_post.scss
> Navbar + cover image should match the viewport height 

- assets/css/_navbar.scss
> Correct navbar white indicator position

- assets/css/_post.scss
> Changed font style for post

- lib/elephant_in_the_room/sites/sites.ex
> Fix popular amount of widgets

- assets/css/_post.scss
- lib/elephant_in_the_room_web/templates/post/public_show.html.eex
> Category list restyled

- assets/js/app.js
- assets/js/markdown_editor.js
> Fixed trying to insert markdown editor everywhere

- assets/css/_navbar.scss
- assets/css/_post.scss
- assets/css/app.scss
- lib/elephant_in_the_room_web/templates/author/public_show.html.eex
- lib/elephant_in_the_room_web/templates/post/public_show.html.eex
- lib/elephant_in_the_room_web/templates/site/public_show.html.eex
- lib/elephant_in_the_room_web/templates/tag/public_show.html.eex
#366 
- Fixes floating footer
- Fixes problem in administration navbar
> Minor css fixes

- lib/elephant_in_the_room_web/templates/site/form.html.eex
- lib/elephant_in_the_room_web/templates/site/index.html.eex
- lib/elephant_in_the_room_web/templates/site/show.html.eex
- lib/elephant_in_the_room_web/utils/utils.ex
Clicking in the site name redirect you directly to the site
Now is possible to delete a site (#368)
> Site buttons

- assets/css/_landing_page.scss
- lib/elephant_in_the_room_web/templates/site/_popular.html.eex
- lib/elephant_in_the_room_web/templates/site/public_show.html.eex
> Site's landing page layout

- README.md
> README update for how to config default sites

- docker-compose.yml
> Binded Redis port to localhost

- assets/css/_post.scss
#399
- Space between paragraphs increased.
- Font size increased
> Update post font size and spacing

- lib/elephant_in_the_room/auth/auth.ex
- lib/elephant_in_the_room/auth/user.ex
- lib/elephant_in_the_room_web/controllers/user_controller.ex
> Make impossible to delete the administrator user

- assets/css/app.scss
> Ensure footer at bottom

- lib/elephant_in_the_room_web/templates/site/public_show.html.eex
> Prevent layout from breaking

- lib/elephant_in_the_room_web/templates/site/_ads.html.eex
> Remove ads title

- assets/css/_landing_page.scss
- lib/elephant_in_the_room/sites/site.ex
- lib/elephant_in_the_room_web/faker/site.ex
- lib/elephant_in_the_room_web/templates/site/_ads.html.eex
- lib/elephant_in_the_room_web/templates/site/form.html.eex
- lib/elephant_in_the_room_web/templates/site/public_show.html.eex
- priv/repo/migrations/20180222205253_create_sites.exs
> Custom ads title

- assets/package-lock.json
- assets/package.json
> fix npm dependencies

- Makefile
- README.md
> Makefile targets

- assets/css/app.scss
- lib/elephant_in_the_room_web/templates/ad/form.html.eex
- lib/elephant_in_the_room_web/templates/author/form.html.eex
- lib/elephant_in_the_room_web/templates/category/form.html.eex
- lib/elephant_in_the_room_web/templates/magazine/form.html.eex
- lib/elephant_in_the_room_web/templates/post/form.html.eex
- lib/elephant_in_the_room_web/templates/role/form.html.eex
- lib/elephant_in_the_room_web/templates/site/form.html.eex
- lib/elephant_in_the_room_web/templates/tag/form.html.eex
- lib/elephant_in_the_room_web/templates/user/form.html.eex
> Added required field mark to forms
